name: simquantgen tests 🧬

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]
jobs:
  build:
    runs-on: [ubuntu-latest, macos-latest, windows-latest]
    strategy:
      matrix:
        r-version: ['4.3.1']

    steps:
      - uses: actions/checkout@v3
      - uses: r-lib/actions/setup-r@v2
      - name: Install dependencies on Ubuntu
        run: |
          sudo apt install -y libcurl4-openssl-dev libharfbuzz-dev libfribidi-dev
      - name: Install dependencies
        run: |
          install.packages(c("devtools", "rextendr", "testthat", "doParallel", "foreach", "txtplot"))
        shell: Rscript {0}
      - name: Test
        run: |
          devtools::load_all()
          devtools::document()
          devtools::test()
        shell: Rscript {0}